version: "2"

services:  
  kong-database:  
    restart: on-failure
    image: cassandra:3
    container_name: kong-database
    ports:
      - "9042:9042"
    volumes:
        - /E/pensee/dockerdata/kongtest/kongdatabase.data:/var/lib/cassandra/data
  kong:  
    restart: on-failure
    image: kong:latest
    container_name: kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - kong-database
    environment:
        - KONG_DATABASE=cassandra
        - KONG_CASSANDRA_CONTACT_POINTS=kong-database
        - KONG_PG_HOST=kong-database
    volumes:
        - /E/pensee/dockerdata/kongtest/kong.logs:/usr/local/kong/logs
  kong-dashboard:  
    restart: on-failure
    image: pgbi/kong-dashboard
    container_name: kong-dashboard
    ports:
      - "8080:8080"